### ISSUE TITLE
feat: add unit under dsc section to homepage

### ISSUE THREAD

**Issue by Visethboti** [avevotsira/dsc#113]
At home page on the bottom, add a section that contain links to the websites of other units under DSC.

**Comment by avevotsira** [comment]
Please tell me they have website and link for these?

**Comment by Visethboti** [comment]
There are 4 units under dsc, each will have their own website and functions.
They want to have a section in home page that have links to each of those 4 units like website by ministry of economy https://mef.gov.kh/

![Screenshot from 2024-07-23 06-37-31](https://github.com/user-attachments/assets/796eeb81-9350-43ae-a5cb-8710d5639ca0)
