### ISSUE TITLE
feat: seperate structure page into dsc and dsc's general secretariat

### ISSUE THREAD

**Issue by Visethboti** [avevotsira/dsc#117]
In structure page, the committee members and organization structure diagram is in one section under the dsc organization structure.
The general secretary and their deputy is in a different section called dsc's general secretary organization structure

**Comment by avevotsira** [comment]
![image](https://github.com/user-attachments/assets/0cce26f6-5ea2-4263-bb49-d67d0b0fded0)

**Comment by avevotsira** [comment]
![image](https://github.com/user-attachments/assets/2ff19070-a15f-47a0-ab4b-2225ab1457f1)

<section>
<header>
<h2><h2>
<p><p>
<header>
<h3><h3>
<h3><h3>
<section>
