### ISSUE TITLE
feat(footer): external link

### ISSUE THREAD

**Issue by avevotsira** [avevotsira/dsc#96]
scope also including the social link:

accept criteria:

- You would want to create a new enum to store those external link. eg: tiktok,mptc .....
- Replace all the link with the workable one , for social media , since we dont have it yet , you can just put it in a place holder as mentioned in first one.

**Comment by Uchita-Hikaru** [comment]
as it is only used in one component, does it need to create an enum just for that

what about sth like this 
`const links = [
{label: t("link.sth), link: sth.gov.kh}
]`

**Comment by avevotsira** [comment]
Should be , it for consistency.  With your code , you'll need an as const.

**Comment by avevotsira** [comment]
Example code.  // OtherLinks.ts

export const enum OtherLinks {
  Facebook = "/facebook",
  Twitter = "/twitter",
  LinkedIn = "/linkedin",
  Instagram = "/instagram",
  YouTube = "/youtube"
}

export const OtherLinkLabels: Record<OtherLinks, string> = {
  [OtherLinks.Facebook]: "Facebook",
  [OtherLinks.Twitter]: "Twitter",
  [OtherLinks.LinkedIn]: "LinkedIn",
  [OtherLinks.Instagram]: "Instagram",
  [OtherLinks.YouTube]: "YouTube"
};

export interface OtherLinkType {
  href: OtherLinks;
  label: string;
}

export function getOtherLink(link: OtherLinks): OtherLinkType {
  return {
    href: link,
    label: OtherLinkLabels[link]
  };
}

export const AllOtherLinks: OtherLinkType[] = Object.values(OtherLinks).map(getOtherLink);




import React from 'react';
import { AllOtherLinks } from './OtherLinks';

const OtherLinksComponent: React.FC = () => {
  return (
    <ul>
      {AllOtherLinks.map((link) => (
        <li key={link.href}>
          <a href={link.href}>{link.label}</a>
        </li>
      ))}
    </ul>
  );
};

export default OtherLinksComponent;
